#!/usr/bin/php
<?php
/**
 * @file
 *
 * Determines the branch a commit is being made against by running bit branch
 * and parseing the output looking for the '*' indicator. Then compares the 
 * branch name against a items in the $blacklist variable and forbids the
 * commit it's being made against one of those branches.
 */

// array of branch names on which commits should be forbidden
$blacklist = array(
  'master',
  'test',
);

exec('git branch', $branches);

foreach ($branches as $branch) {
  if (($astPos = strpos($branch, '*')) !== FALSE) {

    // get the name of the branch, excluding the *
    $branchName = strtolower(trim(substr($branch, $astPos +1)));

    // if commit is on a branch in blacklist, forbid the commit
    if (in_array($branchName, $blacklist)) {
      echo "You may not commit to this branch" . PHP_EOL;
      exit(1);
    }
   
    // commit is on an allowed branch
    exit(0);
  }
}

?>
