#!/usr/bin/php
<?php
/**
 * @file
 *
 * Gets the branch name from refs/HEAD and compares the 
 * branch name against items in the $blacklist variable and forbids the
 * commit it's being made against one of those branches.
 */

// array of branch names on which commits should be forbidden
$blacklist = array(
  'master',
  'test',
);

$refHead = exec('git symbolic-ref HEAD');

$branchName = strtolower(end(explode('/', $refHead)));

// if commit is on a branch in blacklist, forbid the commit
if (in_array($branchName, $blacklist)) {
  echo "You may not commit to this branch" . PHP_EOL;
  exit(1);
}
   
// commit is on an allowed branch
exit(0);
?>
